  - debug: msg="Looking up AWS details"

  - ec2_vpc_net_facts:
      region: "{{region}}"
    register: vpc_facts

  - set_fact: vpc="{{vpc_facts.vpcs[0].id}}"

  - debug:
      msg: "Using {{vpc}} from available vpc's {{vpc_facts.vpcs}}"
      verbosity: 1

  - debug:
      msg: "Using {{vpc}} from available vpc's {{vpc_facts.vpcs[0].tags['Name'] | default('') }} {{vpc_facts.vpcs[0].cidr_block }}"
      verbosity: 0


  - set_fact: play_groups="{{play_hosts |  play_groups(groups, hostvars) }}"

  - ec2_vpc_subnet_facts:
      region: "{{region}}"
    register: all_subnets

  - set_fact: all_subnets="{{all_subnets.subnets}}"
  - set_fact: zones="{{all_subnets | map(attribute='availability_zone') | unique | list }}"

  - debug: var=zones verbosity=1
  - set_fact: subnets="{{all_subnets | map(attribute='id') | list }}"
  - debug: var=subnets verbosity=1

  - set_fact:
      subnet_map: "{{ all_subnets | parse_subnets}}"

  - debug: var=subnet_map verbosity=1

  - name: lookup all security groups
    ec2_group_facts:
      region: "{{region}}"
    delegate_to: localhost
    run_once: true
    register: sg

  - name: map security groups to name=>id
    set_fact:
      sg_groups: "{{sg.security_groups|json_query('[*].{id: group_id, name: group_name}') | to_map( 'name', 'id') }}"

  - debug: var=sg_groups verbosity=1